"""Added level to SkillWarriorLink

Revision ID: cf7b01c44f6a
Revises: 
Create Date: 2025-03-30 21:38:47.383914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf7b01c44f6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill')
    op.drop_table('warrior')
    op.drop_table('skillwarriorlink')
    op.drop_table('profession')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('profession_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='profession_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('skillwarriorlink',
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warrior_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='skillwarriorlink_skill_id_fkey'),
    sa.ForeignKeyConstraint(['warrior_id'], ['warrior.id'], name='skillwarriorlink_warrior_id_fkey'),
    sa.PrimaryKeyConstraint('skill_id', 'warrior_id', name='skillwarriorlink_pkey')
    )
    op.create_table('warrior',
    sa.Column('race', postgresql.ENUM('director', 'worker', 'junior', name='racetype'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profession_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], name='warrior_profession_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='warrior_pkey')
    )
    op.create_table('skill',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skill_pkey')
    )
    # ### end Alembic commands ###
